#!/usr/bin/env bash
set -euo pipefail

repo_name="${REPO_NAME:-wzj-$(basename "$PWD")}"
branch_name="${BRANCH_NAME:-main}"
stamp="$(date +%Y%m%d%H%M%S)"

if ! command -v git >/dev/null 2>&1; then
  echo "git is required" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI gh is required" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "GitHub CLI is not authenticated. Run: gh auth login -h github.com" >&2
  exit 2
fi

mkdir -p docs examples/runtime-notes

cat > "docs/extension-${stamp}.md" <<EOF
# Extension ${stamp}

This file was generated by scripts/02-add-files-commit.sh.

- Repository: ${repo_name}
- Directory: $(basename "$PWD")
- Purpose: demonstrate a second commit after the initial scaffold.
EOF

cat > "examples/runtime-notes/backend-${stamp}.http" <<EOF
GET http://localhost:8080/api/tasks
Accept: application/json

###
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Created from an HTTP example"
}
EOF

cat > "examples/runtime-notes/frontend-${stamp}.txt" <<EOF
Run frontend:
cd frontend
npm install
npm run dev

Run backend:
cd backend
mvn spring-boot:run
EOF

git add docs examples

if git diff --cached --quiet; then
  echo "No files changed; nothing to commit."
  exit 0
fi

git commit -m "docs: add sample extension files"
git push origin "$branch_name"

repo_url="$(gh repo view "$repo_name" --json url -q .url)"
commit_id="$(git rev-parse HEAD)"

echo "REPO_NAME=$repo_name"
echo "COMMIT_ID=$commit_id"
echo "COMMIT_URL=$repo_url/commit/$commit_id"
